esphome:
  name: comando
  friendly_name: Comando

external_components:
  - source:
      type: git
      url: https://github.com/folhas99/esp_cc1101
      ref: main
    components: [cc1101]

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "A/Dpurgiz0l7cXY46ufChLQtZYQp8nGbekpwAHiZkJU="

ota:
  platform: esphome
  password: "58c46ac6784c51b3725b376ac8651599"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  fast_connect: true
  ap:
    ssid: "Comando Fallback Hotspot"
    password: "ygLCE3gnAzK1"

cc1101:
    id: transciver
    sck_pin: 18
    miso_pin: 19
    mosi_pin: 23
    csn_pin: 5
    gdo0_pin: 32
    gdo2_pin: 33
    bandwidth: 200
    frequency: 433.92

remote_transmitter:
  - pin: GPIO32
    carrier_duty_percent: 100%

remote_receiver:
  - pin: GPIO33
    dump: byronsx

button:
  - platform: template
    name: Portao
    id: portao
    on_press:
      - lambda: get_cc1101(transciver)->beginTransmission();
      - remote_transmitter.transmit_byronsx:
          address: 0x000000BC
          command: 0x05
          repeat:
            times: 10
            wait_time: 5ms
      - lambda: get_cc1101(transciver)->endTransmission();

  - platform: template
    name: Garagem
    id: garagem
    on_press:
      - lambda: get_cc1101(transciver)->beginTransmission();
      - remote_transmitter.transmit_byronsx:
          address: 0x000000BC
          command: 0x09
          repeat:
            times: 10
            wait_time: 5ms
      - lambda: get_cc1101(transciver)->endTransmission();
