esphome:
  name: comando
  friendly_name: Comando
  libraries:
    - SPI
    - "SmartRC-CC1101-Driver-Lib"

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ./components
    components: [cc1101_transceiver]

logger:

api:
  encryption:
    key: "YourKey"

ota:
  platform: esphome
  password: "YourPASSWORD"

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  fast_connect: true
  ap:
    ssid: "Comando Fallback Hotspot"
    password: "YourPASSWORD"

cc1101_transceiver:
  id: transciver
  sck: 18
  miso: 19
  mosi: 23
  csn: 5
  gdo0: 32
  gdo2: 33
  frequency: 433.92
  bandwidth: 200

remote_transmitter:
  pin: GPIO32
  carrier_duty_percent: 100%

remote_receiver:
  pin: GPIO33
  #dump: raw
  dump: byronsx

button:
  - platform: template
    name: "Portao"
    on_press:
      - lambda: |-
          id(transciver).beginTransmission();
      - remote_transmitter.transmit_byronsx:
          address: 0x000000BC
          command: 0x05
          repeat:
            times: 10
            wait_time: 5ms
      - lambda: |-
          id(transciver).endTransmission();

#  - platform: template
#    name: "Garagem"
#    on_press:
#      - lambda: |-
#          id(transciver).beginTransmission();
#      - remote_transmitter.transmit_byronsx:
#          address: 0x000000BC
#          command: 0x09
#          repeat:
#            times: 10
#            wait_time: 5ms
#      - lambda: |-
#          id(transciver).endTransmission();
